import '../styles/globals.css'
import 'bootstrap/dist/css/bootstrap.css';
import type { AppProps } from 'next/app'
import Head from 'next/head'
import { useEffect } from 'react'

import WeatherContextProvider from '../store/weather-context'

export default function App({ Component, pageProps }: AppProps) {
  useEffect(()=>{
    require("bootstrap/dist/js/bootstrap");
},[])

  return <WeatherContextProvider>
    <Head>
      <title>Weather - Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>
    
    
    <Component {...pageProps} />
  </WeatherContextProvider> 
}
